language: node_js

node_js:
    - "0.10"
    - "0.12"

script:
  - npm test

# taken from istanbul .travis.yml: https://github.com/gotwarlost/istanbul/blob/master/.travis.yml
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
